### ISSUE TITLE
Make a "Candidate" component that shows the candidates nicely

### ISSUE THREAD

**Issue by cecton** [rustminded/recruit-rust#6]

**Comment by yozhgoor** [comment]
To avoid repetition, what you think about a profile component ?

**Comment by yozhgoor** [comment]
![Screenshot 2021-02-27 at 20 50 31](https://user-images.githubusercontent.com/63659479/109398478-7d794e80-793d-11eb-960c-4eb823a88cf7.png)
At this time

**Comment by cecton** [comment]
We don't have preview on netlify yet?

I just added it to netlify on my account but we might need to do the same trick than yewprint to avoid extra cost in build time. I will create a ticket for this.

**Comment by yozhgoor** [comment]
I have think at this issues lately, wanted to do it when the profile was merge before

**Comment by cecton** [comment]
Sure
